name: Python Script

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
  #   For Debug into the runner image 
  #  - name: Start tmate session
  #    uses: mxschmitt/action-tmate@v3


    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Python script
      run: echo "1" | python ucf.py
      working-directory: ${{ github.workspace }}

    - name: Save coupons.txt as artifact
      uses: actions/upload-artifact@v2
      with:
        name: coupons
        path: coupons.txt
