name: Udemy Coupons Fetcher

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
  #   For Debug into the runner image 
  #  - name: Start tmate session
  #    uses: mxschmitt/action-tmate@v3


    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Python script
      run: python ucf_ci.py
      working-directory: ${{ github.workspace }}

    - name: Save coupons.txt as artifact
      uses: actions/upload-artifact@v3
      with:
        name: coupons
        path: coupons.txt
